### ISSUE TITLE
WP Bouncer doesn't seem to be working

### ISSUE THREAD

**Issue by nickchomey** [crowdsecurity/cs-wordpress-bouncer#100]
I no longer get the error mentioned in https://github.com/crowdsecurity/cs-wordpress-bouncer/issues/91, however crowdsec doesn't seem to be working. I added my IP address to the decisions list but don't get bounced with this image 

![image](https://user-images.githubusercontent.com/88559987/173196004-a35b4ba7-427c-4ba5-a4fe-1147c9067929.png)

(found in this great tutorial which you might want to incorporate into your documentation -https://anto.online/guides/setup-crowdsec-wordpress-reverse-proxy-docker/)

**Comment by julienloizelet** [comment]
Hi,

This kind of line :
```
time="11-06-2022 10:22:47" level=info msg="127.0.0.1 - [Sat, 11 Jun 2022 10:22:47 CST] \"GET /v1/decisions?ip=108.162.216.208 HTTP/1.1 200 3.387217ms \"WordPress CrowdSec Bouncer/v1.5.0\" \""
```

suggests that the WordPress plugin is at least trying to bounce an IP (108.162.216.208 in this example).

The `/var/log/crowdsec_api.log` is the log file of the CrowdSec agent itself.

We will find more useful information in the log files of the WordPress plugin : you should find a `prod.log` in a folder `wp-content/plugins/cs-wordpress-bouncer/logs`. 

Please also enable the debug log option in your plugin (see `Enable debug mode` in the Advanced settings) in order to find a more verbose `debug.log` file in the same folder.

Could you please share the content of this debug.log file that appears when you access your website with an IP that should be banned ?

Thanks

**Comment by julienloizelet** [comment]
Hi,
This kind of line : 
```
2022-06-16T20:50:33.428664+00:00|300|{"type":"NON_AUTHORIZED_X_FORWARDED_FOR_USAGE","original_ip":"cloudflare.ip.address","x_forwarded_for_ip":"my.laptop.ip.address"}
```
shows that the WP bouncer does not know that you are using a proxy with the IP address `cloudflare.ip.address`.

So, the WP Bouncer is trying to bounce the  `cloudflare.ip.address` and not your `my.laptop.ip.address` (and the result is a "bypass").

Could you add the `cloudflare.ip.address` IP to the WP Bouncer settings :  `Advanced -> Remediations -> Trust these CDN Ips` ?

Please, let me know if it's better after that.

p.s: The WP Bouncer can work without the Cloudfare bouncer, but it should not harm to use both. Unfortunately, I don't know how this Cloudfare bouncer is working, and I won't be able to help you for this part.

**Comment by julienloizelet** [comment]
Hi,
it seems that the WP bouncer is now bouncing the LAPTOP.IP as expected.

It asks the LAPI to get the remediation for this IP and the result is "bypass".

If you want to test a ban for example, you have to add a decision for this (you can use the cscli command line tool)


If you want to check all the active decisions : 
```
cscli decisions list
```
If you want to add a ban decision for the LAPTOP.IP: 
```
cscli decisions add --scope Ip --value LAPTOP.IP  --duration 4h --type ban
```

If you want to retrieve a decision for this specific LAPTOP.IP:

```
cscli decisions list -i LAPTOP.IP
```

If you want to delete a decision for this specific LAPTOP.IP:


```
cscli decisions delete -i LAPTOP.IP
```

As I see in the logs, "clean" IP decisions are cached for 5 seconds, and "bad" IP decisions are cached for 20s, so you should wait  between a decision modification and refreshing your browser to see the result.


If all is ok, you should see for example a ban wall if you add a ban decision for your LAPTOP.IP.

Please let me know.

**Comment by julienloizelet** [comment]
Closing this ticket for now. Feel free to reopen if the problem still exists. Thank you.
