### ISSUE TITLE
[Feature Request] Multisite Support with Global Tables

### ISSUE THREAD

**Issue by taropaa** [crowdsecurity/cs-wordpress-bouncer#128]
Hi, it would be nice if multisite could be supported to facilitate easier deployment and management across networks. 

It could work like this:

1. The plugin checks if it's network enabled. If yes, then store the settings network-wide. or
2. Add support for constants that can be declared in wp-config.php (should help with automated deployments as well) or
3. both

Thank you for considering.

**Comment by julienloizelet** [comment]
Thanks for your message.

Will look into this WordPress "Multisite" feature to see what we could do.

**Comment by bilyboy785** [comment]
Hi @julienloizelet 

There is any support for wordpress constants to configure many websites at same time ?

**Comment by julienloizelet** [comment]
> There is any support for wordpress constants to configure many websites at same time ?

Hi @bilyboy785, not for now.

Thanks

**Comment by julienloizelet** [comment]
Hi @taropaa ,
I just released a `2.5.0` version of the plugin that supports Multisite installation: 
- Plugin has to be network activated
- we store and use settings in the `wp_sitemeta` table (instead of the `wp_options` table for a single WordPress installation).


Thanks
