### ISSUE TITLE
ive enabled crowdsec on my wp site 

### ISSUE THREAD

**Issue by regchanuk** [crowdsecurity/cs-wordpress-bouncer#132]
i access site via normal domain and it gets killed no error 

so i have domain 
123456.uk example
i have cloudflare enabled 
ive had bouncing flex or normal enabled my sit gets blocked
still not working 

im using uptime kuma here for monitoring still stumpped
![image](https://user-images.githubusercontent.com/46360316/222896742-9d1100d6-2b2f-4f10-a760-fd6e8d3dfaa3.png)

**Comment by julienloizelet** [comment]
Hi,

I am not sure to understand your issue.

What do you mean by "i access site via normal domain and it gets killed no error" ?

And the domain 123456.uk does not seem to exist.

By the way, could you please share some error logs if you have any ?

For example, when you say "my sit gets blocked", do you have any PHP, apache or nginx errors logs ?

Can you enable the debug mode ( (Advanced -> Enable debug mode) and see if there is more useful message in the `wp-content/plugins/crowdsec/logs` folder ?

Thanks

**Comment by julienloizelet** [comment]
Closing, happy to continue the conversation here or elsewhere.
