### ISSUE TITLE
Call toString on null

### ISSUE THREAD

**Issue by Maxence1502** [crowdsecurity/cs-wordpress-bouncer#41]
Hello!
I have this error in my apache2 logs :
`PHP Fatal error:  Uncaught Error: Call to a member function toString() on null in /var/www/html/wp-content/plugins/crowdsec/vendor/crowdsec/bouncer/src/ApiCache.php:350\nStack trace:\n#0 /var/www/html/wp-content/plugins/crowdsec/vendor/crowdsec/bouncer/src/ApiCache.php(491): CrowdSecBouncer\\ApiCache->removeRemediations()\n#1 /var/www/html/wp-content/plugins/crowdsec/vendor/crowdsec/bouncer/src/Bouncer.php(181): CrowdSecBouncer\\ApiCache->pullUpdates()\n#2 /var/www/html/wp-content/plugins/crowdsec/inc/scheduling.php(23): CrowdSecBouncer\\Bouncer->refreshBlocklistCache()\n#3 /var/www/html/wp-includes/class-wp-hook.php(303): crowdSecRefreshBlocklist()\n#4 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()\n#5 /var/www/html/wp-includes/plugin.php(518): WP_Hook->do_action()\n#6 /var/www/html/wp-cron.php(138): do_action_ref_array()\n#7 {main}\n  thrown in /var/www/html/wp-content/plugins/crowdsec/vendor/crowdsec/bouncer/src/ApiCache.php on line 350, referer: https://my-website.com/wp-cron.php?doing_wp_cron=1629730782.3094000816345214843750`

**Comment by mobula9** [comment]
Duplicate of #40

**Comment by Maxence1502** [comment]
I'm not sure this is a duplicate.
The #40 is a problem when deactivating the plugin
The #41 (this one) appears periodically at each CRON of wordpress/crowdsec
