### ISSUE TITLE
CRITICAL Uncaught Error: Call to a member function error() on null in /wp-content/plugins/crowdsec/inc/Bounce.php:339

### ISSUE THREAD

**Issue by luutan04** [crowdsecurity/cs-wordpress-bouncer#90]
Access woocomerce log from this url: /wp-admin/admin.php?page=wc-status&tab=logs, I saw a long list of CRITICAL Uncaught Error such as below:

2022-05-10T22:50:22+00:00 CRITICAL Uncaught Error: Call to a member function error() on null in /var/www/mydomain/htdocs/wp-content/plugins/crowdsec/inc/Bounce.php:339
Stack trace:
#0 /var/www/mydomain/htdocs/wp-content/plugins/crowdsec/inc/bounce-current-ip.php(27): Bounce->safelyBounce()
#1 /var/www/mydomain/htdocs/wp-includes/class-wp-hook.php(307): safelyBounceCurrentIp()
#2 /var/www/mydomain/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /var/www/mydomain/htdocs/wp-includes/plugin.php(474): WP_Hook->do_action()
#4 /var/www/mydomain/htdocs/wp-settings.php(450): do_action()
#5 /var/www/mydomain/wp-config.php(113): require_once('...')
#6 /var/www/mydomain/htdocs/wp-load.php(55): require_once('...')
#7 /var/www/mydomain/htdocs/wp-cron.php(44): require_once('...')
#8 {main}
  thrown in /var/www/mydomain/htdocs/wp-content/plugins/crowdsec/inc/Bounce.php on line 339

**Comment by sabban** [comment]
Hi,
Can you share your wordpress version and the crowdsec plugin version ?

**Comment by luutan04** [comment]
Hi,

WordPress, woocommerce and crowdsec plugin are latest version.
Wordpress: 5.9.3
Woocommerce: 6.5.0
Crowdsec: 1.4.1

- Bouncing level: Normal
- Stream mode

My best guess that when rankmath SEO cron job run, it was causing this error

**Comment by julienloizelet** [comment]
Thanks for reporting this.
We will try to debug this as soon as possible.

**Comment by julienloizelet** [comment]
Hi @luutan04,
I just released a `1.4.2` version on of the crowdsec plugin : this will not solve the issue, but you should find more relevant error messages in your `wp_content/debug.log` file (assuming the `WP_DEBUG` and `WP_DEBUG_LOG` constants are defined to true).

Those messages should begin with `safelyBounce error:`.

Could you please use the `1.4.2` version and share the messages you will find in your `debug.log` ?

**Comment by julienloizelet** [comment]
Hi @luutan04 
I just released a `1.4.3` version of the crowdsec plugin : it should avoid the error.
Could you please try it ?

**Comment by luutan04** [comment]
I don't see the error in logs anymore!
