### ISSUE TITLE
Change to user agent reported to crowdsec_api.log to include the site name

### ISSUE THREAD

**Issue by cRUSHr2012** [crowdsecurity/cs-wordpress-bouncer#95]
When reading the **crowsdesc_api.log**, it can be useful to know which site made the request. Maybe a custom ID, or the site name added to the user agent ?

`time="14-05-2022 12:10:14" level=info msg="127.0.0.1 - [Sat, 14 May 2022 12:10:14 EEST] \"GET /v1/decisions/stream?startup=false&scopes=Ip%2CRange HTTP/1.0 200 116.225231ms \"WordPress CrowdSec Bouncer/v1.4.3\" \""`

**Comment by julienloizelet** [comment]
Hi,

I understand your need and will see with the core team if we can add a custom data (at the end of the user agent for example) or if we have to use an extra parameter.

We could add another optional configuration to do that.

**Comment by raykai** [comment]
This would be very useful!

**Comment by julienloizelet** [comment]
Hi, 

With the last 2.1.0 release, there is now a setting called `Custom User-Agent` in `Advanced settings -> Debug mode `

You can fill this field with some alphanumeric characters (maximum 5). This allows to see different user agent when reading the Crowdsec logs.
